/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  Addresses,
  AddressesInterface,
} from "../../EternisVerifier.sol/Addresses";

const _abi = [
  {
    inputs: [],
    name: "ARBITRUM_MAINNET",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BASE_MAINNET",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BNB_MAINNET",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LINEA_TESTNET",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OPTIMISM_GOERLI_TESTNET",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OPTIMISM_MAINNET",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PLOYGON_MUMBAI_TESTNET",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "POLYGON_MAINNET",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6102d9610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100925760003560e01c8063975b95ba11610065578063975b95ba1461010f578063b1c661351461012d578063c0f474841461014b578063fbf953091461016957610092565b806363b0c90714610097578063833df64f146100b55780638d1c4533146100d3578063923e10d9146100f1575b600080fd5b61009f610187565b6040516100ac9190610288565b60405180910390f35b6100bd61019f565b6040516100ca9190610288565b60405180910390f35b6100db6101b7565b6040516100e89190610288565b60405180910390f35b6100f96101cf565b6040516101069190610288565b60405180910390f35b6101176101e7565b6040516101249190610288565b60405180910390f35b6101356101ff565b6040516101429190610288565b60405180910390f35b610153610217565b6040516101609190610288565b60405180910390f35b61017161022f565b60405161017e9190610288565b60405180910390f35b73ace04e6deb9567c1b8f37d113f2da9e690fc128d81565b731bbb0896ac6f4e32a89157c73fb830325a441cb981565b73e79a453bd088f4a58656b315a7c1f8ea3473ccf181565b73d6534f52ceb3d0139b915bc0c3278a94687fa5c781565b73e79a453bd088f4a58656b315a7c1f8ea3473ccf181565b73f223e215b2c9a2e5fe1b2971d5694684b2e734c181565b73d6534f52ceb3d0139b915bc0c3278a94687fa5c781565b732f0306d698685bef7ff50745bff7178f0d117ba881565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061027282610247565b9050919050565b61028281610267565b82525050565b600060208201905061029d6000830184610279565b9291505056fea2646970667358221220f85ced7a8b7eb6d039f3859313798b880768f402317ffa8a2aed1042ecbdadc164736f6c63430008140033";

type AddressesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AddressesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Addresses__factory extends ContractFactory {
  constructor(...args: AddressesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Addresses & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Addresses__factory {
    return super.connect(runner) as Addresses__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AddressesInterface {
    return new Interface(_abi) as AddressesInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Addresses {
    return new Contract(address, _abi, runner) as unknown as Addresses;
  }
}
